// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CloudinaryUtilityInterface is an autogenerated mock type for the CloudinaryUtilityInterface type
type CloudinaryUtilityInterface struct {
	mock.Mock
}

// UploadAvatar provides a mock function with given fields: _a0, _a1
func (_m *CloudinaryUtilityInterface) UploadAvatar(_a0 echo.Context, _a1 int) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCloudinaryUtilityInterface creates a new instance of CloudinaryUtilityInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudinaryUtilityInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudinaryUtilityInterface {
	mock := &CloudinaryUtilityInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
