// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidatorErrorInterface is an autogenerated mock type for the ValidatorErrorInterface type
type ValidatorErrorInterface struct {
	mock.Mock
}

// Struct provides a mock function with given fields: _a0
func (_m *ValidatorErrorInterface) Struct(_a0 interface{}) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewValidatorErrorInterface creates a new instance of ValidatorErrorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidatorErrorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidatorErrorInterface {
	mock := &ValidatorErrorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
